services:


  mariadb-musiquiz:
    image: mariadb:latest
    container_name: mariadb-musiquiz
    ports: 
      - "${MYSQL_PORT}:3306"
    environment: 
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./server/tests/test-setup.sql:/docker-entrypoint-initdb.d/init.sql:ro
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5


  backend: 
    image: ghcr.io/t-clement/musiquiz-backend:latest
    container_name: backend-musiquiz
    ports: 
      # - "${DOCKER_PORT_API}:3000"
      - "3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MONGODB_ATLAS_URI=${MONGODB_ATLAS_URI}
      - FRONT_URL=${FRONT_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - TOKEN_EXPIRATION=${TOKEN_EXPIRATION}
      - REFRESH_EXPIRATION=${REFRESH_EXPIRATION}
    # depends_on:
    #   mariadb-musiquiz:
    #     condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/api/ping"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5   

  frontend: 
    image: ghcr.io/t-clement/musiquiz-frontend:latest
    container_name: frontend-musiquiz
    ports: 
      # - "${DOCKER_PORT_FRONT}:80"
      - "80"
    # depends_on: 
    #   backend: 
    #     condition: service_healthy


    
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro #place la config du reverse proxy
    # depends_on:
    #   frontend:
    #     condition: service_healthy
    #   backend:
    #     condition: service_healthy