version: '3'
services:

  mariadb-musiquiz:
    image: mariadb:latest
    container_name: mariadb-musiquiz
    ports: 
      - "${MYSQL_PORT}:3306"
    environment: 
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./server/tests/test-setup.sql:/docker-entrypoint-initdb.d/init.sql:ro
  backend: 
    image: ghcr.io/t-clement/musiquiz-backend:latest
    container_name: backend-musiquiz
    ports: 
      - "${DOCKER_PORT_API}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MONGODB_ATLAS_URI=${MONGODB_ATLAS_URI}
    depends_on:
      - mariadb-musiquiz
  frontend: 
    image: ghcr.io/t-clement/musiquiz-frontend:latest
    container_name: frontend-musiquiz
    ports: 
      - "${DOCKER_PORT_FRONT}:80"
    depends_on: 
      - backend